language: cpp
os: osx
compiler: clang
osx_image: xcode9.1

matrix:
  include:

# CoreGraphics/Cocoa on MacOSX
    - brew_packages: libpng

      before_script:
        - mkdir build
        - cd build
        - curl -# -o clang6_0_0.tar.xz http://releases.llvm.org/6.0.0/clang+llvm-6.0.0-x86_64-apple-darwin.tar.xz
        - tar -xJf clang6_0_0.tar.xz
        - mv clang+llvm-6.0.0-x86_64-apple-darwin clang

      script:
        - export CXXFLAGS="-nostdinc++ -isystem$TRAVIS_BUILD_DIR/build/clang/include/c++/v1"
        - export LDFLAGS="-L$TRAVIS_BUILD_DIR/build/clang/lib -Wl,-rpath,$TRAVIS_BUILD_DIR/build/clang/lib"
        - export CTEST_OUTPUT_ON_FAILURE="1"
        - cmake -G "Unix Makefiles" --config Debug -DCMAKE_BUILD_TYPE=Debug -DIO2D_BACKEND=COREGRAPHICS_MAC ../.
        - make tests
        - ctest -V -C Debug

# Cairo/Xlib on MacOSX
    - before_script:
        - mkdir build
        - cd build
        - curl -# -o clang6_0_0.tar.xz http://releases.llvm.org/6.0.0/clang+llvm-6.0.0-x86_64-apple-darwin.tar.xz
        - tar -xJf clang6_0_0.tar.xz
        - mv clang+llvm-6.0.0-x86_64-apple-darwin clang
        - export COLUMNS=80
        - curl -LO https://raw.githubusercontent.com/GiovanniBussi/macports-ci/master/macports-ci
        - chmod +x ./macports-ci
        - ./macports-ci install
        - PATH="/opt/local/bin:$PATH"
        - sudo port -N -k install cairo +x11
        - brew install libpng graphicsmagick

      script:
        - export CXXFLAGS="-nostdinc++ -isystem$TRAVIS_BUILD_DIR/build/clang/include/c++/v1 -isystem/opt/X11/include -isystem/opt/local/include -isystem/usr/local/include"
        - export LDFLAGS="-L$TRAVIS_BUILD_DIR/build/clang/lib -Wl,-rpath,$TRAVIS_BUILD_DIR/build/clang/lib -L/opt/X11/lib -L/opt/local/lib -L/usr/local/lib"
        - export CTEST_OUTPUT_ON_FAILURE="1"
        - cmake -G "Unix Makefiles" --config Debug -DCMAKE_BUILD_TYPE=Debug -DIO2D_BACKEND=CAIRO_XLIB ../.
        - make tests
        - ctest -V -C Debug
