os:
  - Visual Studio 2017

install:
  - choco upgrade git -y
  - git submodule update --init --recursive
  - vcpkg install cairo:x64-windows-static
  - vcpkg install graphicsmagick:x64-windows-static
  - vcpkg install graphicsmagick:x64-windows-static

platform:
  - x64

configuration:
  - Debug

before_build:
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"
  - mkdir %CONFIGURATION%
  - cd %CONFIGURATION%
  - cmake -G "Visual Studio 15 2017 Win64" --config %CONFIGURATION% "-DCMAKE_BUILD_TYPE=%CONFIGURATION%" -DIO2D_BACKEND=CAIRO_WIN32 "-DCMAKE_TOOLCHAIN_FILE=c:/tools/vcpkg/scripts/buildsystems/vcpkg.cmake" "-DVCPKG_TARGET_TRIPLET=x64-windows-static" ../.

build_script:
  - msbuild io2d.sln /t:tests /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

test_script:
  - ctest -V -C %CONFIGURATION%
