os:
  - Visual Studio 2017

environment:
    matrix:
        - vcpkg_triplet: x64-windows
          cmake_generator: "Visual Studio 15 2017 Win64"
          platform: x64

        - vcpkg_triplet: x86-windows
          cmake_generator: "Visual Studio 15 2017"
          platform: x86



install:
  - git submodule update --init --recursive
  - vcpkg install cairo:%vcpkg_triplet%
  - vcpkg install graphicsmagick:%vcpkg_triplet%
 
configuration:
  - Debug
 
before_build:
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"
  - mkdir %CONFIGURATION%
  - cd %CONFIGURATION%
  - cmake -G "%cmake_generator%" --config %CONFIGURATION% "-DCMAKE_BUILD_TYPE=%CONFIGURATION%" -DIO2D_DEFAULT=CAIRO_WIN32 "-DCMAKE_TOOLCHAIN_FILE=c:/tools/vcpkg/scripts/buildsystems/vcpkg.cmake" "-DVCPKG_TARGET_TRIPLET=%vcpkg_triplet%" ../.

build_script:
  - msbuild io2d.sln /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

test_script:
  - ctest -V -C %CONFIGURATION%
